import {
    toItem,
    canEquip,
    toSlot,
    mallPrice,
    autosellPrice,
    print
} from 'kolmafia';

const MAX_COUNT = 10;

const PANTS = ['Drunkula\'s silky pants',
    'Great Wolf\'s beastly trousers',
    'Mayor Ghost\'s khakis',
    'Unkillable Skeleton\'s shinguards',
    'Warms-Your-Tush',
    'zombie mariachi pants',
    'cool iron greaves',
    'warbear bearserker greaves',
    'warbear electric long johns',
    'warbear high festival pants',
    'weedy skirt',
    'drafty drawers',
    'dubious loincloth',
    'muddy skirt',
    'transparent pants',
    'antique greaves',
    'big pants',
    'BRAINS shorts',
    'Brimstone Boxers',
    'Chester\'s cutoffs',
    'corroded breeches',
    'crappy Mer-kin tailpiece',
    'cursed breeches',
    'Danglin\' Chad\'s loincloth',
    'Dinsey\'s pants',
    'eelskin pants',
    'El Vibrato leg guards',
    'extremely skinny jeans',
    'foam naval trousers',
    'hardened slime pants',
    'hobo dungarees',
    'Hodgman\'s lobsterskin pants',
    'Jeans of Loathing',
    'Jodhpurs of Violence',
    'The Jokester\'s pants',
    'leggings of the Spider Queen',
    'Mer-kin gladiator tailpiece',
    'Mer-kin scholar tailpiece',
    'mutant legs',
    'mostly rat-hide leggings',
    'the Archwizard\'s briefs',
    'The Ghoul King\'s ghoulottes',
    'The Necbromancer\'s Shorts',
    'Ol\' Scratch\'s ol\' britches',
    'old patched suit-pants',
    'Oscus\'s dumpster waders',
    'Oscus\'s flypaper pants',
    'Pantaloons of Hatred',
    'pink pinkslip slip',
    'poodle skirt',
    'repaid diaper',
    'scale-mail underwear',
    'sea chaps',
    'slime-covered greaves',
    'square sponge pants',
    'troutsers',
    'Uncle Hobo\'s gift baggy pants',
    'Wal-Mart overalls',
    'Zombo\'s grievous greaves',
    'duct tape dockers',
    'flowing hippy skirt',
    'plexiglass pants',
    'astronaut pants',
    'honeybritches',
    'bullet-proof corduroys',
    'distressed denim pants',
    'gauze shorts',
    'ghast iron codpiece',
    'lynyrdskin breeches',
    'dwarvish war kilt',
    'pygmy briefs',
    'snailmail breeches',
    'star pants',
    'black greaves',
    'leather chaps',
    'sealhide leggings',
    'bloodied surgical dungarees',
    'giant discarded torn-up glove',
    'plaid skirt',
    'red silk skirt',
    'antique nutcracker pants',
    'baggy rave pants',
    'bauxite boxers',
    'biomechanical crimborg leg armor',
    'buoybottoms',
    'clingfilm trousers',
    'Daisy\'s unclean bloomers',
    'fire hose',
    'floral-print skirt',
    'furry kilt',
    'furry pants',
    'furry skirt',
    'Grimacite gaiters',
    'Radio Free Pants',
    'ratskin pajama pants',
    'rusty metal greaves',
    'slime waders',
    'spangly mariachi pants',
    'Voluminous Radio Pants',
    'warbear ceremonial party pants',
    'warbear fleece-lined long johns',
    'warbear officer greaves',
    'alpha-mail pants',
    'palm-frond capris',
    'yakskin kilt',
    'yakskin pants',
    'yakskin skirt',
    'hippopotamus kilt',
    'hippopotamus pants',
    'hippopotamus skirt',
    'Angelhair Culottes',
    'Crimbylow-rise jeans',
    'eldritch pants',
    'Galapagosian Cuisses',
    'Grimacite greaves',
    'Krakrox\'s Loincloth',
    'Lederhosen of the Night',
    'Newman\'s Own Trousers',
    'Volartta\'s bellbottoms',
    'bakelite breeches',
    'boneana hammock',
    'Greaves of the Murk Lord',
    'Oil slacks',
    'marble maebari',
    'penguin shorts',
    'penguinskin mini-kilt',
    'penguinskin mini-skirt',
    'porcelain plus-fours',
    'terra cotta trousers',
    'wrought-iron waders',
    'Dress pants',
    'Troll britches',
    '1337 7r0uZ0RZ',
    'troutpiece',
    'Whoompa Fur Pants',
    'wooly loincloth',
    'bankruptcy barrel',
    'bounty-hunting pants',
    'bowlegged pants',
    'Brogre brorts',
    'burning paper jorts',
    'burnt snowpants',
    'cane-mail pants',
    'Crimbo pants',
    'depleted Grimacite shinguards',
    'discarded swimming trunks',
    'fancy tuxedo pants',
    'floaty rock pants',
    'gold lamé pants',
    'Greatest American Pants',
    'gym shorts',
    'lava-proof pants',
    'liar\'s pants',
    'makeshift skirt',
    'Moonthril Greaves',
    'ninjammies',
    'old school Mafia knickerbockers',
    'Pantsgiving',
    'papier-mâchuridars',
    'psychic\'s pslacks',
    'pteruges',
    'saffron antaravasaka',
    'snakeskin thighboots',
    'snowboarder pants',
    'space beast fur pants',
    'Spelunker\'s khakis',
    'Spooky Putty leotard',
    'stinky cheese diaper',
    'sugar shorts',
    'Three Mile Island shorts',
    'thunder down underwear',
    'time trousers',
    'Travoltan trousers',
    'tree skirt',
    'Tropical Crimbo Shorts',
    'Vicar\'s Tutu',
    'warbear dress greaves',
    'wumpus-hair loincloth',
    'Xiblaxian stealth trousers',
    'BRICKO pants',
    'Can-Can skirt',
    'Cerebral Culottes',
    'leotarrrd',
    'pig-iron shinguards',
    'stainless steel slacks',
    'hot daub stand',
    'clockwork pants',
    'gnauga hide chaps',
    'gnauga hide kilt',
    'gnauga hide skirt',
    'grass skirt',
    'miner\'s pants',
    'paper-plate-mail pants',
    'SMOOCH codpiece',
    'swashbuckling pants',
    'turtlemail breeches',
    'weasel stomping pants',
    'crotchety pants',
    'fancy party pants',
    'pair of plants',
    'The Sagittarian\'s leisure pants',
    'demonskin trousers',
    'double-ice britches',
    'monster pants',
    'ninja hot pants',
    'Boss Bat britches',
    'filthy corduroys',
    'junk trunks',
    'Knob Goblin elite pants',
    'Orcish cargo shorts',
    'trousers of the white knight',
    'los chinos',
    'manly bloomers',
    'astral shorts',
    'astral trousers',
    'bloody clown pants',
    'bottoms of the barrel',
    'chalk chinos',
    'cheerful pajama pants',
    'gabardine gaiters',
    'genie\'s pants',
    'gingerbread trousers',
    'government-issued slacks',
    'hep waders',
    'lemon drop trousers',
    'miming corduroys',
    'paperclip pants',
    'paraffin palazzos',
    'pixel pants',
    'polyester pettipants',
    'pottery training pants',
    'primitive alien loincloth',
    'servo-assisted exo-pants',
    'smooth velvet pants',
    'snow pants',
    'sucker hakama',
    'tinsel tights',
    'topiary tights',
    'toy Crimbot rocket legs',
    'union scalemail pants',
    'warbear battle greaves',
    'warbear long johns',
    'warbear party pants',
    'wax pants',
    'wicker knickers',
    'Knob Goblin Uberpants',
    'sticky meat kilt',
    'sticky meat pants',
    'sticky meat skirt',
    'bark boxers',
    'basic meat kilt',
    'basic meat pants',
    'basic meat skirt',
    'ironic jogging shorts',
    'stylish swimsuit',
    'tighty whiteys',
    'turtle wax greaves',
    'white satin pants',
    'frilly skirt',
    'pants of the Slug Lord',
    'bugbear bungguard',
    'chain-mail monokini',
    'Cloaca-Cola fatigues',
    'dungeoneer\'s dungarees',
    'Dyspepsi-Cola fatigues',
    'parasitic tentacles',
    'pin-stripe slacks',
    'barskin loincloth',
    'Knob Goblin pants',
    'brown paper pants',
    'studded leather boxer shorts',
    'three-legged pants',
    'Leapin\' Trousers',
    'exo-servo leg braces',
    'dice-print pajama pants',
    'electronic dulcimer pants',
    'The Emperor\'s new pants',
    'Knob Goblin harem pants',
    'mariachi pants',
    'old sweatpants',
    'spandex anniversary shorts',
    'conspicuous lack of pants',
    'Guild Pants',
]

const SHIRTS = ['Unkillable Skeleton\'s breastplate',
    'cool iron breastplate',
    'chamoisole',
    'Chester\'s muscle shirt',
    'Dragonscale breastplate',
    'dreadful sweater',
    'extra-see-thru nightie',
    'extremely wet T-shirt',
    'Hodgman\'s disgusting technicolor overcoat',
    'letterman\'s jacket',
    'Mer-kin breastplate',
    'sea salt scrubs',
    'shark jumper',
    'witch\'s bra',
    'duct tape shirt',
    'bat-ass leather jacket',
    'asbestos apron',
    'lynyrdskin tunic',
    'snailmail hauberk',
    'star shirt',
    'midriff scrubs',
    'red coat',
    'unrequired jacket',
    'Kashmir sweater',
    'surgical apron',
    'antique nutcracker waistcoat',
    'Grimacite gown',
    'grungy flannel shirt',
    'hairshirt',
    'Othello\'s military jacket',
    'red shirt',
    'spangly mariachi vest',
    'punk rock jacket',
    'Colonel Mustard\'s Lonely Spades Club Jacket',
    'Corporal Fennel\'s Lonely Clubs Club Jacket',
    'General Sage\'s Lonely Diamonds Club Jacket',
    'Private Pepper\'s Lonely Hearts Club Jacket',
    'Grimacite guayabera',
    'hipposkin poncho',
    'Stephen\'s lab coat',
    'yak anorak',
    'ghost toga',
    'wumpus-hair sweater',
    'bronze breastplate',
    'SMOOCH breastplate',
    '"Humorous" T-shirt',
    'bod-ice',
    'Brogre brolo shirt',
    'camouflage T-shirt',
    'cane-mail shirt',
    'coconut bikini top',
    'famous blue raincoat',
    'flaming pink shirt',
    'floral print shirt',
    'gingham blouse',
    'gladiator tunica',
    'goth kid t-shirt',
    'Gregarious Gregorian Smock',
    'Moonthril Cuirass',
    'origami pasties',
    'psycho sweater',
    'rhinestone cowboy shirt',
    'Sneaky Pete\'s leather jacket',
    'Sneaky Pete\'s leather jacket (collar popped)',
    'souvenir ski t-shirt',
    'sugar shirt',
    'tuxedo shirt',
    'Ultracolor™ shirt',
    'Xiblaxian stealth vest',
    'Ye Olde Navy Fleece',
    'ASCII shirt',
    'eXtreme Bi-Polar Fleece Vest',
    'clockwork trench coat',
    'conquistador\'s breastplate',
    'demonskin jacket',
    'flyest of shirts',
    'gnauga hide vest',
    'icing poncho',
    'turtlemail hauberk',
    'Grateful Undead T-shirt',
    'safety vest',
    'white hat hacker T-shirt',
    'clownskin harness',
    'junk-mail shirt',
    'astral shirt',
    'birdbone corset',
    'chest barrel',
    'lemon shirt',
    'pirate shirt',
    'red-and-green sweater',
    'smooth velvet bra',
    'smooth velvet shirt',
    'supportive bra',
    'loathing eagle baby-doll shirt',
    'soggy wofl t-shirt',
    'white snakeskin duster',
    'filthy hippy poncho',
    'metal band T-shirt',
    'Knob Goblin elite shirt',
    'BGE \'cuddly critter\' shirt',
    'BGE \'ferocious fruit\' shirt',
    'Mr. Shirt',
    'harem girl t-shirt',
    'fishbone corset',
    'frilly shirt',
    'Ascension Souvenir T-Shirt',
    'anniversary safety glass vest',
    'The Emperor\'s new shirt',
    'Kiss the Knob apron',
    'Professor What T-Shirt',
    'Thinknerd T-Shirt',
    'Radio Free Jersey']

const BACK_ITEMS = ['anniversary pewter cape',
    'antique nutcracker cape',
    'auxiliary backbone',
    'bakelite backpack',
    'barskin cloak',
    'black cloak',
    'Buddy Bjorn',
    'Camp Scout backpack',
    'carpe',
    'chalk chlamys',
    'Cloak of Dire Shadows',
    'cod cape',
    'dice-shaped backpack',
    'Drapes-You-Regally',
    'Drunkula\'s cape',
    'Duke Vampire\'s regal cloak',
    'Elf army poncho',
    'fiberglass frock',
    'frozen turtle shell',
    'gabardine gunnysack',
    'ghost shawl',
    'giant gym membership card',
    'Great S-Cape',
    'hemp backpack',
    'kelp-holly drape',
    'jetpack',
    'Lavalos\'s shell',
    'little deuce cape',
    'Lord Flameface\'s cloak',
    'LOV Epaulettes',
    'makeshift cape',
    'marble mantle',
    'Mayor Ghost\'s cloak',
    'Misty Cape',
    'Misty Cloak',
    'Misty Robe',
    'Mr. Container',
    'Newbiesport™ backpack',
    'octolus-skin cloak',
    'oil shell',
    'old SCUBA tank',
    'palm-frond cloak',
    'paperclip cape',
    'paraffin poncho',
    'pillow shell',
    'polyester parachute',
    'porcelain pelerine',
    'Protonic accelerator pack',
    'Rad cloak',
    'Rain-Doh red wings',
    'rubber cape',
    'saffron uttarasanga',
    'sea cape',
    'sea mantle',
    'sea shawl',
    'sealhide cloak',
    'shellacked shell',
    'shocked shell',
    'Size XI Wizard\'s Robe',
    'smoker\'s cloak',
    'spant backplate',
    'super-absorbent tarp',
    'TÎ¤◊lisman of Baiø‡',
    'teddybear backpack',
    'terra cotta train',
    'Time Bandit Time Towel',
    'Time Cape',
    'Time Cloak',
    'toy jet pack',
    'vampyric cloake',
    'whatsit-covered turtle shell',
    'wicker slicker',
    'wings of fire',
    'yellow cape']

const ACCESSORY = ['BOOtonniere',
    'Chester\'s Aquarius medallion',
    'Chester\'s moustache',
    'Chester\'s sunglasses',
    'corncob pipe',
    'crusty hula hoop',
    'cursed ring finger ring',
    'cursed scrunchie',
    'dead guy\'s memento',
    'Dreadsylvania Auditor\'s badge',
    'eerie fetish',
    'frayed rope belt',
    'Frosty\'s carrot',
    'grandfather watch',
    'guts necklace',
    'hardened slime belt',
    'hobo stogie',
    'Hodgman\'s bow tie',
    'Hodgman\'s lucky sock',
    'hopping socks',
    'lucky bottlecap',
    'Mesmereyes@trade; contact lenses',
    'moon-amber necklace',
    'mime army infiltration glove',
    'mime army insignia (cryonics)',
    'mime army insignia (espionage)',
    'mime army insignia (infantry)',
    'mime army insignia (intelligence)',
    'mime army insignia (morale)',
    'mime army insignia (psychological warfare)',
    'mime army insignia (pyrotechnics)',
    'mime army insignia (sanitation)',
    'Mr. Joe\'s bangles',
    'Ol\' Scratch\'s manacles',
    'old ball and chain',
    'old soft shoes',
    'Oscus\'s pelt',
    'rainbow pearl earring',
    'rainbow pearl necklace',
    'rainbow pearl ring',
    'rickety old unicycle',
    'rope with some soap on it',
    'slime-covered necklace',
    'tonguebone',
    'Uncle Hobo\'s belt',
    'Uncle Hobo\'s epic beard',
    'Uncle Hobo\'s fingerless tinsel gloves',
    'vial of hot blood',
    'warm fur',
    'Zombo\'s skull ring',
    'baneful bandolier',
    'Belt of Loathing',
    'malevolent medallion',
    'Pocket Square of Loathing',
    'Treads of Loathing',
    'Ass-Stompers of Violence',
    'Fuzzy Slippers of Hatred',
    'Girdle of Hatred',
    'Novelty Belt Buckle of Violence',
    'warbear electric warscarf',
    'warbear nuclear bowtie',
    'warbear polarized goggles',
    'Dinsey\'s glove',
    'Dinsey\'s oculus',
    'Drunkula\'s ring of haze',
    'Helps-You-Sleep',
    'HOA zombie eyes',
    'Mayor Ghost\'s sash',
    'Protects-Your-Junk',
    'Quiets-Your-Steps',
    'Aluminum Epsilon of Humility',
    'amber aviator shades',
    'aquamariner\'s necklace',
    'aquamariner\'s ring',
    'Blue Diamond of Honesty',
    'Copper Alpha of Sincerity',
    'diving muff',
    'fudgecycle',
    'Green Clover of Justice',
    'hare pin',
    'Iron Beta of Industry',
    'jam band',
    'Lead Zeta of Chastity',
    'long-forgotten necklace',
    'Mer-kin dragbelt',
    'Mer-kin eyeglasses',
    'Mer-kin gutgirdle',
    'Mer-kin prayerbeads',
    'Mer-kin thighguard',
    'Mer-kin waistrope',
    'Nickel Gamma of Frugality',
    'Orange Star of Sacrifice',
    'Order of the Silver Wossname',
    'ornamental sextant',
    'pearl diver\'s necklace',
    'pearl diver\'s ring',
    'Pink Heart of Spirit',
    'Purple Horseshoe of Honor',
    'Red Balloon of Valor',
    'sea holster',
    'shark tooth necklace',
    'stinky fannypack',
    'teflon swim fins',
    'Uranium Omega of Temperance',
    'velcro boots',
    'vinyl boots',
    'water-polo mitt',
    'Yellow Moon of Compassion',
    'Zinc Delta of Tranquility',
    'booty chest charrrm bracelet',
    'cannonball charrrm bracelet',
    'copper ha\'penny charrrm bracelet',
    'round green sunglasses',
    'shiny hood ornament',
    'silver tongue charrrm bracelet',
    'blackberry combat boots',
    'blackberry galoshes',
    'blackberry moccasins',
    'blackberry slippers',
    'Elmley shades',
    'energy drink IV',
    'furniture dolly',
    'gearbox necklace',
    'plexiglass pendant',
    'plexiglass pinky ring',
    'plexiglass pocketwatch',
    'ratskin belt',
    'rusty chain necklace',
    'Spacegate diplomat\'s insignia',
    'Spacegate military insignia',
    'Spacegate scientist\'s insignia',
    'spark plug earring',
    'woven baling wire bracelets',
    'wrench bracelet',
    'Gaia beads',
    'hippy medical kit',
    'attorney\'s badge',
    'bejeweled pledge pin',
    'round purple sunglasses',
    'Ankh of Badahnkadh',
    'Iiti Kitty phone charm',
    'bewitching boots',
    'bitter bowtie',
    'bottle opener belt buckle',
    'brazen bracelet',
    'compression stocking',
    'headhunter necktie',
    'hippy protest button',
    'Jefferson wings',
    'kick-ass kicks',
    'Lockenstock@trade; sandals',
    'molten medallion',
    'monstrous monocle',
    'musty moccasins',
    'red masque',
    'sealhide belt',
    'sealhide gloves',
    'sealhide moccasins',
    'sphygmomanometer',
    'head mirror',
    'pygmy nose-bone',
    'surgical mask',
    'black belt',
    'candy necklace',
    'Choker of the Ultragoth',
    'clingfilm slippers',
    'cyborg stompin\' boot',
    'Earring of Fire',
    'glowing red eye',
    'groovy prism necklace',
    'grumpy old man charrrm bracelet',
    'Ice-Cold Aluminum Necklace',
    'Ice-Cold Beer Ring',
    'Ice-Cold Beerring',
    'Lord Soggyraven\'s Slippers',
    'Mudflap-Girl Earring',
    'Mudflap-Girl Necklace',
    'Mudflap-Girl Ring',
    'Nose Ring of Putrescence',
    'The One Mood Ring',
    'pacifier necklace',
    'Pendant of Fire',
    'Pendant of Gargalesis',
    'pirate fledges',
    'Putrid Pendant',
    'red badge',
    'The Ring',
    'Ring of Fire',
    'Ring of the Sewer Snake',
    'Sketcherz@trade;',
    'sneakeasies',
    'sock garters',
    'solid gold pegleg',
    'tarrrnished charrrm bracelet',
    'Unspeakable Earring',
    'warbear fleece-lined warscarf',
    'warbear plasma bowtie',
    'warbear snowblindness goggles',
    'spaghetti cult rosary',
    'Bram\'s choker',
    'Former Sheriff Dan\'s tin star',
    'glass eye',
    'heart of the volcano',
    'mafia pointer finger ring',
    'plaid pocket square',
    'pogo stick',
    'Red Fox glove',
    'ring of the Skeleton Lord',
    'sardine can key',
    'spiky turtle shoulderpads',
    'super-strong air freshener',
    'Wal-Mart nametag',
    'shamanic beads',
    'vampire pearl earring',
    'witch wart',
    'Bandolier of the Spaghetti Elemental',
    'beaten-up Chucks',
    'bejeweled cufflinks',
    'Bling of the New Wave',
    'bone spurs',
    'chintzy accordion pin',
    'chintzy disco ball pendant',
    'chintzy noodle ring',
    'chintzy saucepan earring',
    'chintzy seal pendant',
    'chintzy turtle brooch',
    'Claw of the Infernal Seal',
    'enormous hoop earring',
    'Garter of the Turtle Poacher',
    'giant motorcycle boots',
    'Gravyskin Belt of the Sauceblob',
    'La Hebilla del Cinturón de Lopez',
    'Mafia middle finger ring',
    'Slow Talkin\' Elliot\'s dogtags',
    'tube sock',
    'badge of authority',
    'bakelite badge',
    'bakelite belt',
    'bakelite brooch',
    'belt of Ogrekind',
    'eXtreme mittens',
    'fiberglass fannypack',
    'fiberglass fingerguard',
    'filigreed hamethyst earring',
    'filigreed hamethyst necklace',
    'filigreed hamethyst ring',
    'Krampus Horn',
    'Lord Spookyraven\'s ear trumpet',
    'mafia thumb ring',
    'marble magnet',
    'marble medallion',
    'Master Thief\'s utility belt',
    'porcelain phantom mask',
    'pulled porquoise earring',
    'pulled porquoise pendant',
    'pulled porquoise ring',
    'red shoe',
    'rum barrel charrrm bracelet',
    'solid baconstone earring',
    'solid baconstone necklace',
    'solid baconstone ring',
    'tarnished tastevin',
    'terra cotta tie tack',
    'terra cotta truss',
    'the Ley Incursion\'s waist',
    'wrought-iron walker',
    'wrought-iron widget',
    'wrought-iron winch crank',
    'Yuleviathan necklace',
    'Duskwalker fangs',
    'amulet of extreme plot significance',
    'ankleweights',
    'badass belt',
    'bezoar ring',
    'Caveman Dan\'s favorite rock',
    'cement shoes',
    'Claybender glasses',
    'colored-light "necklace"',
    'crystal belt buckle',
    'doll-eye amulet',
    'droll monocle',
    'fancy black tie',
    'flapper floppers',
    'floaty rock necklace',
    'giant pinky ring',
    'heat-resistant gloves',
    'heat-resistant necktie',
    'hockey stick of furious angry rage',
    'imitation nice watch',
    'Mafia bow tie',
    'Mafia stogie',
    'mafia pinky ring',
    'Mr. Cheeng\'s spectacles',
    'numberwang',
    'outlaw bandana',
    'Roman sadnals',
    'Space Trip safety headphones',
    'streetfighting champion\'s belt',
    'support cummerbund',
    'tiny plastic four-shadowed mime',
    'tiny plastic Naughty Sorceress',
    'vampire pearl necklace',
    'vampire pearl ring',
    'warbear dress bracers',
    'white earbuds',
    'orc wrist',
    'SMOOCH spaulders',
    'antique nutcracker beard',
    'antique nutcracker boots',
    'antique nutcracker epaulets',
    'barrel beryl choker',
    'barrel beryl nose ring',
    'barrel beryl ring',
    'Brimstone Bracelet',
    'Brimstone Brooch',
    'Emblem of Ak\'gyxoth',
    'expensive camera',
    'Fancy Jeff\'s fancy pocket square',
    'Frown Exerciser',
    'gnatwing earring',
    'mafia organizer badge',
    'Othello\'s handkerchief',
    'pig-iron bracers',
    'SMOOCH kneepads',
    'stainless steel scarf',
    'stainless steel solitaire',
    'stainless steel suspenders',
    'stolen necklace',
    'tap shoes',
    'tortoboggan',
    'Voluminous Radio Sneakers',
    'worksite credentials',
    'screwing pooch',
    'SMOOCH bracers',
    'Bonerdagon necklace',
    'Boris\'s ring',
    'depleted Grimacite astrolabe',
    'depleted Grimacite grappling hook',
    'depleted Grimacite weightlifting belt',
    'enchanted toothpick',
    'freshwater pearl necklace',
    'gingerbeard',
    'Jarlsberg\'s earring',
    'The Lost Glasses',
    'ring of adornment',
    'ring of aggravate monster',
    'ring of cold resistance',
    'ring of conflict',
    'ring of fire resistance',
    'ring of gain strength',
    'ring of increase damage',
    'ring of teleportation',
    'shiny tribal beads',
    'Sneaky Pete\'s breath spray',
    'stuffed shoulder parrot',
    'Talisman o\' Namsilat',
    'phase-tuned shield generator belt',
    'Saccharine Maple pendant',
    'UV monocular',
    'arrrgyle socks',
    'beach glass necklace',
    'candy dress shoes',
    'candy necktie',
    'cheap sunglasses',
    'chocolate pocketwatch',
    'Codpiece of the Goblin King',
    'Crimbolex watch',
    'jangly bracelet',
    'hemp string',
    'Jolly Roger charrrm bracelet',
    'papier-masque',
    'peace-sign necklace',
    'phat turquoise bracelet',
    'ribbon candy ascot',
    'sk8board',
    'soggy elf shoes',
    'spant shoulderpads',
    'Boss Bat bling',
    'duonoculars',
    'Grimacite galoshes',
    'Grimacite garter',
    'Grimacite gorget',
    'albatross necklace',
    'anemoney clip',
    'enchanted handwarmer',
    'ghost of a necklace',
    'Grimacite gauntlets',
    'Grimacite girdle',
    'Grimacite go-go boots',
    'imp unity ring',
    'infernal insoles',
    'junk band',
    'lucky cat collar',
    'lucky rabbit\'s foot',
    'MagiMechTech NanoMechaMech',
    'perfume-soaked bandana',
    'spooky glove',
    'tin star',
    'toy crazy train',
    'toy maglev monorail',
    'toy train',
    'wristwatch of the white knight',
    'bottlecap turtle',
    'rubber gloves',
    'whalebone corset',
    'elevennis shoes',
    'acid-squirting flower',
    'baconstone bracelet',
    'baconstone earring',
    'baconstone pendant',
    'baconstone ring',
    'Baron von Ratsworth\'s money clip',
    'Baron von Ratsworth\'s monocle',
    'battle broom',
    'bauxite bow-tie',
    'big red clown nose',
    'C.A.R.N.I.V.O.R.E. button',
    'cement sandals',
    'clown shoes',
    'clownskin belt',
    'dead guy\'s watch',
    'disbelief suspenders',
    'eXtreme nose ring',
    'garish pinky ring',
    'genie\'s bracers',
    'glow-in-the-dark necklace',
    'gnoll-tooth necklace',
    'gumshoes',
    'hamethyst bracelet',
    'hamethyst earring',
    'hamethyst necklace',
    'hamethyst ring',
    'moustache sock',
    'Mr. Screege\'s spectacles',
    'natty blue ascot',
    'night-vision goggles',
    'nicksilver ring',
    'Pine-Fresh air freshener',
    'polka-dot bow tie',
    'porquoise bracelet',
    'porquoise eyebrow ring',
    'porquoise necklace',
    'porquoise ring',
    'power sock',
    'nicksilver ring',
    'Sasq@trade; watch',
    'Scandalously Skimpy Bikini',
    'severed rocking horse head',
    'shiny ring',
    'sicksilver ring',
    'slicksilver ring',
    'smooth velvet hanky',
    'smooth velvet pocket square',
    'smooth velvet socks',
    'snow belly',
    'sour ball and chain',
    'Spookyraven signet',
    'steel knuckles',
    'string of moist beads',
    'thicksilver ring',
    'ticksilver ring',
    'tie-dyed fannypack',
    'tiny plastic Bugbear Captain',
    'tiny plastic Dr. Awkward',
    'tiny plastic Ed the Undying',
    'tiny plastic Lord Flameface',
    'tiny plastic Lord Spookyraven',
    'tiny plastic protector spectre',
    'tiny plastic Rene C. Corman',
    'training belt',
    'training legwarmers',
    'walrus-tusk earring',
    'warbear goggles',
    'warbear laser bowtie',
    'warbear warscarf',
    'wool sock',
    'wicksilver ring',
    'boxing glove',
    'dope gangsta bling-bling',
    'furry green earmuffs',
    'oven mitts',
    'bark bracelet',
    'bejeweled accordion strap',
    'chocolate rabbit\'s foot',
    'ironic oversized sunglasses',
    'ladle of mystery',
    'tiny plastic Susie',
    'white belt',
    'ye olde golde frontes',
    'mafia wedding ring',
    '"I Voted!" sticker',
    'actual reality goggles',
    'aerogel anvil',
    'aerogel apron',
    'aerogel ascot',
    'Amulet of Yendor',
    'anniversary balsa wood socks',
    'anniversary burlap belt',
    'Annual Ascot',
    'Anti-earplugs',
    'astral belt',
    'astral bracer',
    'astral mask',
    'astral ring',
    'bananarama bangle',
    'banjo kazoo mount',
    'barrel hoop earring',
    'batskin belt',
    'beer goggles',
    'Belt of Howling Anger',
    'BGE pocket calendar',
    'BGE tiny plastic toy',
    'black glass',
    'blue glowstick',
    'blue plastic baby',
    'blue ribbon',
    'Boots of Twilight Whispers',
    'broken clock',
    'bronze detective badge',
    'Brutal brogues',
    'brown plastic baby',
    'bugbear communicator badge',
    'bugbear detector',
    'burning paper slippers',
    'Cat-Herding Prod',
    'cheap elven gloves',
    'cheap studded belt',
    'chalk chain',
    'chalk choker',
    'club necklace',
    'coarse hemp socks',
    'codpiece',
    'consolation ribbon',
    'continuum transfunctioner',
    'Counterclockwise Watch',
    'CRIMBCO lanyard',
    'Crimbomega drive chain',
    'crying statue earrings',
    'crystalline seal eye',
    'dark baconstone ring',
    'dark hamethyst ring',
    'dark porquoise ring',
    'defective Golden Mr. Accessory',
    'dethklok',
    'diamond necklace',
    'dice belt buckle',
    'dice ring',
    'dice sunglasses',
    'dirty hobo gloves',
    'discarded bowtie',
    'disembodied smile',
    'dorky glasses',
    'Draftsman\'s driving gloves',
    'Dyspepsi-Cola-issue canteen',
    'E.M.U. Unit',
    'elven socks',
    'El Vibrato translator',
    'Elvish sunglasses',
    'encoder ring',
    'ESP suppression collar',
    'evil flaming eyeball pendant',
    'exclusive ultra-rare item',
    'FantasyRealm G. E. M.',
    'first-aid pouch',
    'fishbone belt',
    'fishbone bracers',
    'fishbone facemask',
    'fishbone fins',
    'fishbone kneepads',
    'flashing novelty button',
    'flask flops',
    'foam noodle',
    'fossilized necklace',
    'French slippers',
    'frosty halo',
    'fudge pocket square',
    'furry halo',
    'fuzzy bracelets',
    'gabardine garland',
    'gabardine girdle',
    'gabardine gloves',
    'Garland of Greatness',
    'Gary Claybender\'s Time Screwer',
    'gate transceiver',
    'Gauntlets of the Blood Moon',
    'giant designer sunglasses',
    'giant diamond ring',
    'gingerservo',
    'glacial clock',
    'glow-in-the-dark wristwatch',
    'gold detective badge',
    'gold wedding ring',
    'Golden Mr. Accessory',
    'Golden Mr. Eh?',
    'government-issued necktie',
    'government-issued night-vision goggles',
    'GPS-tracking wristwatch',
    'gray bow tie',
    'green glowstick',
    'Groll doll',
    'gummi bowtie',
    'haggis socks',
    'Hand in Glove',
    'hand-knitted Crimbo socks',
    'hand-knitted diving booties',
    'hazardous sauce dosimeter',
    'high-friction boots',
    'ice skates',
    'incredibly dense meat gem',
    'inflatable duck',
    'intergalactic pom poms',
    'Item #13',
    'jar of anniversary jam',
    'jaunty feather',
    'Jekyllin hide belt',
    'Juju Mojo Mask',
    'Junior Adventurer\'s merit badge',
    'Junior LAAAAME merit badge',
    'knobby kneepads',
    'KoL Con 8-Bit power bracelet',
    'KoL Con X Bingo Card',
    'Kremlin\'s Greatest Briefcase',
    'kumquartz ring',
    'left half of a heart necklace',
    'Lil\' Doctor@trade; bag',
    'loafers',
    'Loathing Legion necktie',
    'Loathing Legion rollerblades',
    'lollipop cufflinks',
    'Lord Spookyraven\'s spectacles',
    'LOV Earrings',
    'lube-shoes',
    'lucky Crimbo tiki necklace',
    'lucky gold ring',
    'LWA ring',
    'LyleCo premium monocle',
    'makeshift SCUBA gear',
    'Marvelous Unitard',
    'mayfly bait necklace',
    'Mega Gem',
    'memory of a cultist\'s robe',
    'meteorthopedic shoes',
    'mime-proof sunglasses',
    'miming boots',
    'miming gloves',
    'mirrored aviator shades',
    'mini-marshmallow dispenser',
    'monster bait',
    'mood ring',
    'Mr. Accessory',
    'Mr. Accessory Jr.',
    'Mr. Eh?',
    'Mr. Exploiter',
    'Ms. Accessory',
    'mysterious silver lapel pin',
    'navel ring of navel gazing',
    'novelty tattoo sleeves',
    'observational glasses',
    'offensive moustache',
    'old school calculator watch',
    'orange glowstick',
    'orange leather lanyard',
    'over-the-shoulder Folder Holder',
    'pair of government shades',
    'pair of pearidot earrings',
    'paperclip-on tie',
    'paraffin pendant',
    'paraffin punching bag',
    'pat-a-cake pendant',
    'patent leather shoes',
    'Personal Ventilation Unit',
    'pine cone necklace',
    'pink glowstick',
    'pink plastic baby',
    'pirate radio ring',
    'plastic detective badge',
    'plastic Duskwalker necklace',
    'plastic spider ring',
    'plastic vampire fangs',
    'plush sea serpent',
    'Pokëmann figurine: Bloodkip',
    'Pokëmann figurine: Duck',
    'Pokëmann figurine: Frank',
    'Pokëmann figurine: Galumpagump',
    'Pokëmann figurine: Hoboking',
    'Pokëmann figurine: Kagosan',
    'Pokëmann figurine: Magikrap',
    'Pokëmann figurine: Moog',
    'Pokëmann figurine: Nothing',
    'Pokëmann figurine: Porkachu',
    'Pokëmann figurine: Shoggoth',
    'Pokëmann figurine: Smugleaf',
    'Pokëmann figurine: Twitter',
    'Pokëmann figurine: Vegemite',
    'Pokëmann figurine: Vermouth',
    'polyester pulsera',
    'portable cassette player',
    'purple glowstick',
    'Radio KoL Antenna Ball',
    'Radio KoL Bottle Opener',
    'Radio KoL Coffee Mug',
    'Radio KoL Flashlight',
    'Radio KoL Keychain',
    'Radio KoL Maracas',
    'Radio KoL Patch',
    'red armband',
    'red plastic baby',
    'Red Roger\'s red left foot',
    'Red Roger\'s red right foot',
    'red-hot medallion',
    'reinforced furry underpants',
    'ridiculous belt',
    'ridiculous earring',
    'ridiculous sunglasses',
    'right half of a heart necklace',
    'ring of Detect Boring Doors',
    'ring of half-assed regeneration',
    'ring of telling skeletons what to do',
    'rose-colored glasses',
    'rubber WWBBDD? bracelet',
    'rubber WWBD? bracelet',
    'rubber WWJD? bracelet',
    'rubber WWSPD? bracelet',
    'rubber WWtNSD? bracelet',
    'scabrous seal epaulets',
    'seal medal',
    'second-hand knockoff engagement ring',
    'Senior LAAAAME merit badge',
    'shin gourds',
    'shining halo',
    'shock belt',
    'silver detective badge',
    'silent nightlight',
    'Sister Accessory',
    'skeletal scabbard',
    'skeleton skis',
    'slime convention pin',
    'snow belt',
    'soul mask',
    'soul monocle',
    'Source shades',
    'spade necklace',
    'spaghetti cult robe',
    'sparkly engagement ring',
    'special sauce glove',
    'sphygmayomanometer',
    'spiked boots',
    'spirit bell',
    'spring boots',
    'Star of Bravery',
    'stick-on eyebrow piercing',
    'sticky gloves',
    'stinky cheese eye',
    'strawberyl necklace',
    'string of blue beads',
    'string of green beads',
    'string of red beads',
    'stuffed carpenter',
    'stuffed mink',
    'stuffed walrus',
    'Superhero Reboots',
    'sweat socks',
    'Talisman of Baio',
    'Talisman of Bakula',
    'test case',
    'Time Bandit Badge of Courage',
    'time halo',
    'Time Lord Badge of Honor',
    'time-twitching toolbelt',
    'tiny die-cast arc-welding Elfborg',
    'tiny die-cast Bashful the Reindeer',
    'tiny die-cast blade a-spinning',
    'tiny die-cast CrimboTown Toy Factory',
    'tiny die-cast death ray in a pear tree',
    'tiny die-cast Doc the Reindeer',
    'tiny die-cast Don Crimbo',
    'tiny die-cast Dopey the Reindeer',
    'tiny die-cast factory worker elf',
    'tiny die-cast Father Crimbo',
    'tiny die-cast Father Crimborg',
    'tiny die-cast gift-wrapping elf',
    'tiny die-cast golden ring',
    'tiny die-cast goose a-laying',
    'tiny die-cast Grumpy the Reindeer',
    'tiny die-cast Happy the Reindeer',
    'tiny die-cast killing bird',
    'tiny die-cast middle-management elf',
    'tiny die-cast pencil-pusher elf',
    'tiny die-cast ribbon-cutting Elfborg',
    'tiny die-cast Rudolphus of Crimborg',
    'tiny die-cast Sleepy the Reindeer',
    'tiny die-cast Sneezy the Reindeer',
    'tiny die-cast stocking-stuffer elf',
    'tiny die-cast swarm a-swarming',
    'tiny die-cast Swiss hen',
    'tiny die-cast turtle mech',
    'tiny die-cast Uncle Hobo',
    'tiny die-cast Unionize the Elves Sign',
    'tiny die-cast Zeppo the Reindeer',
    'tiny plastic 11 Dealer',
    'tiny plastic 7-foot dwarf',
    'tiny plastic abominable fudgeman',
    'tiny plastic Abuela Crimbo',
    'tiny plastic accordion thief',
    'tiny plastic also a spoiler',
    'tiny plastic ambulatory robo-minecart',
    'tiny plastic Ancient Unspeakable Bugbear',
    'tiny plastic ancient yuletide troll',
    'tiny plastic angry bugbear',
    'tiny plastic angry goat',
    'tiny plastic angry space marine',
    'tiny plastic angry vikings',
    'tiny plastic anime smiley',
    'tiny plastic animelf',
    'tiny plastic apathetic lizardman',
    'tiny plastic astronomer',
    'tiny plastic Axe Wound',
    'tiny plastic baby gravy fairy',
    'tiny plastic bad vibe',
    'tiny plastic Baron von Ratsworth',
    'tiny plastic barrrnacle',
    'tiny plastic batbugbear',
    'tiny plastic Battlesuit Bugbear Type',
    'tiny plastic beanbat',
    'tiny plastic bee swarm',
    'tiny plastic beebee gunners',
    'tiny plastic Beebee King',
    'tiny plastic beebee queue',
    'tiny plastic Beelzebozo',
    'tiny plastic Best Game Ever',
    'tiny plastic Big Candy',
    'tiny plastic bitchin\' meatcar',
    'tiny plastic Black Knight',
    'tiny plastic black ops bugbear',
    'tiny plastic blazing bat',
    'tiny plastic blood-faced volleyball',
    'tiny plastic blooper',
    'tiny plastic Bonerdagon',
    'tiny plastic Boris',
    'tiny plastic Boss Bat',
    'tiny plastic brainsweeper',
    'tiny plastic briefcase bat',
    'tiny plastic bugaboo',
    'tiny plastic buzzerker',
    'tiny plastic Café Elf',
    'tiny plastic Captain Kerkard',
    'tiny plastic cavebugbear',
    'tiny plastic Charity the Zombie Hunter',
    'tiny plastic Cheshire bat',
    'tiny plastic ChibiBuddy@trade;',
    'tiny plastic chunk of depleted Grimacite',
    'tiny plastic Clancy the Minstrel',
    'tiny plastic cocoabo',
    'tiny plastic coffee pixie',
    'tiny plastic colollilossus',
    'tiny plastic conservationist hippy',
    'tiny plastic CRIMBCO HQ',
    'tiny plastic Crimbo Casino',
    'tiny plastic Crimbo elf',
    'tiny plastic Crimbo reindeer',
    'tiny plastic Crimbo wreath',
    'tiny plastic Crimbodhisattva',
    'tiny plastic Crimbomega',
    'tiny plastic Crimbomination',
    'tiny plastic Crimborgatron',
    'tiny plastic Crimbot',
    'tiny plastic Crimboween pentagram',
    'tiny plastic cubist bull',
    'tiny plastic demoninja',
    'tiny plastic disco bandit',
    'tiny plastic Don Crimbo',
    'tiny plastic drunk goat',
    'tiny plastic Duke Starkiller',
    'tiny plastic exo-suited miner',
    'tiny plastic fat stack of cash',
    'tiny plastic Father McGruber',
    'tiny plastic fax machine',
    'tiny plastic Felonia',
    'tiny plastic fiendish can of asparagus',
    'tiny plastic filthy hippy jewelry maker',
    'tiny plastic fire servant',
    'tiny plastic fluffy bunny',
    'tiny plastic fruit golem',
    'tiny plastic Fudge Wizard',
    'tiny plastic fuzzy dice',
    'tiny plastic G Imp',
    'tiny plastic Gaia\'ajh-dsli Ak\'lwej',
    'tiny plastic Gary Claybender',
    'tiny plastic ghost pickle on a stick',
    'tiny plastic ghuol whelp',
    'tiny plastic giant pair of tweezers',
    'tiny plastic gift-wrapping vampire',
    'tiny plastic Gnollish crossdresser',
    'tiny plastic Gnomester Blomester',
    'tiny plastic golden gundam',
    'tiny plastic GORM-8',
    'tiny plastic goth giant',
    'tiny plastic grue',
    'tiny plastic handsome mariachi',
    'tiny plastic Hank North, Photojournalist',
    'tiny plastic Hellion',
    'tiny plastic hermit',
    'tiny plastic hobo elf',
    'tiny plastic howling balloon monkey',
    'tiny plastic hypodermic bugbear',
    'tiny plastic Iiti Kitty',
    'tiny plastic Jared the Duskwalker',
    'tiny plastic Jarlsberg',
    'tiny plastic K.R.A.M.P.U.S.',
    'tiny plastic killer bee',
    'tiny plastic Knob Goblin bean counter',
    'tiny plastic Knob Goblin harem girl',
    'tiny plastic Knob Goblin King',
    'tiny plastic Knob Goblin mad scientist',
    'tiny plastic Knott Yeti',
    'tiny plastic Knows About Chakras',
    'tiny plastic Krampus',
    'tiny plastic lemon-in-the-box',
    'tiny plastic leprechaun',
    'tiny plastic levitating potato',
    'tiny plastic lobsterfrogman',
    'tiny plastic MechaElf',
    'tiny plastic mime executive',
    'tiny plastic mime functionary',
    'tiny plastic mime scientist',
    'tiny plastic mime soldier',
    'tiny plastic Mob Penguin',
    'tiny plastic moneybee',
    'tiny plastic mosquito',
    'tiny plastic Mr. Mination',
    'tiny plastic mumblebee',
    'tiny plastic mutant elf',
    'tiny plastic ninja snowman',
    'tiny plastic Norville Rogers',
    'tiny plastic Orcish Frat Boy',
    'tiny plastic orphan',
    'tiny plastic pastamancer',
    'tiny plastic peacannon',
    'tiny plastic Professor What',
    'tiny plastic Protagonist',
    'tiny plastic Queen Bee',
    'tiny plastic reindeer',
    'tiny plastic Rudolph the Red',
    'tiny plastic sabre-toothed lime',
    'tiny plastic sauceror',
    'tiny plastic scary clown',
    'tiny plastic Scott the Miner',
    'tiny plastic Scream Queen',
    'tiny plastic seal clubber',
    'tiny plastic semi-autonomous drill unit',
    'tiny plastic senile lihc',
    'tiny plastic skeletal reindeer',
    'tiny plastic smarmy pirate',
    'tiny plastic Sneaky Pete',
    'tiny plastic Spam Witch',
    'tiny plastic spiderbugbear',
    'tiny plastic spiny skelelton',
    'tiny plastic spoiler',
    'tiny plastic spooky pirate skeleton',
    'tiny plastic spooky vampire',
    'tiny plastic Spunky Princess',
    'tiny plastic stab bat',
    'tiny plastic star starfish',
    'tiny plastic stocking mimic',
    'tiny plastic strand of DNA',
    'tiny plastic sweet nutcracker',
    'tiny plastic taco cat',
    'tiny plastic taco-clad Crimbo elf',
    'tiny plastic Tammy the Tambourine Elf',
    'tiny plastic The Big Wisniewski',
    'tiny plastic the Free Man',
    'tiny plastic The Man',
    'tiny plastic The Silent Nightmare',
    'tiny plastic topiary golem',
    'tiny plastic Toybot',
    'tiny plastic trollipop',
    'tiny plastic Trouser Snake',
    'tiny plastic turtle tamer',
    'tiny plastic Uncle Crimbo',
    'tiny plastic Uncle Crimboku',
    'tiny plastic undead elbow macaroni',
    'tiny plastic warbear',
    'tiny plastic warbear fortress',
    'tiny plastic warwelf',
    'tiny plastic whitesnake',
    'tiny plastic wild beaver',
    'tiny plastic Wu Tang the Betrayer',
    'tiny plastic XXX pr0n',
    'tiny plastic yes also a spoiler',
    'tiny plastic Your Brain',
    'tiny plastic zmobie',
    'topiary necktie',
    'torquoise ring',
    'tourmalime tourniquet',
    'Uncle Buck',
    'Unstable Pointy Ears',
    'V for Vivala mask',
    'vampire collar',
    'warbear energy bracers',
    'warbear exo-arm',
    'warbear hoverbelt',
    'warbear laser beacon',
    'Warehouse 23 bling',
    'water wings',
    'water wings for babies',
    'wax face',
    'wax hand',
    'wheel',
    'white collar',
    'wicker kickers',
    'wicker ticker',
    'Wrist-Boy',
    'wrought-iron walker',
    'wrought-iron widget',
    'wrought-iron winch crank',
    'Xiblaxian holo-wrist-puter',
    'Xiblaxian xeno-detection goggles',
    'Xlyinia\'s notebook',
    'x-ray specs',
    'Yearbook Club Camera',
    'yellow glowstick',
    'your cowboy boots',
    'zombie monkey necklace'];

const HAT = ['Covers-Your-Head',
    'Great Wolf\'s headband',
    'Mayor Ghost\'s toupee',
    'Thunkula\'s drinking cap',
    'Unkillable Skeleton\'s skullcap',
    'zombie mariachi hat',
    'cool iron helmet',
    'hangman\'s hood',
    'warbear electro-spiked helm',
    'warbear fancy fedora',
    'warbear heated ushanka',
    'Amoon-Ra Cowtep\'s nemes',
    'intimidating coiffure',
    'wolfskull mask',
    'eleven-gallon hat',
    '8-billed baseball cap',
    'Admiral\'s hat',
    'aerated diving helmet',
    'antique helmet',
    'battered old top-hat',
    'biker\'s hat',
    'Brimstone Beret',
    'corrosive cowl',
    'crappy Mer-kin mask',
    'crown-shaped beanie',
    'crumpled felt fedora',
    'cursed eyepatch',
    'Dinsey\'s brain',
    'dreadful fedora',
    'eelskin hat',
    'El Vibrato helmet',
    'electrician\'s hardhat',
    'feathered headdress',
    'foam commodore\'s hat',
    'Frosty\'s old silk hat',
    'ganger bandana',
    'Goggles of Loathing',
    'googly-ball hat',
    'googly-heart hat',
    'googly-star hat',
    'hardened slime hat',
    'hazmat helmet',
    'Hodgman\'s porkpie hat',
    'The Jokester\'s wig',
    'lava balaclava',
    'Lens of Hatred',
    'Lens of Violence',
    'longhaired hippy wig',
    'MAHI fez',
    'Mer-kin bunwig',
    'Mer-kin facecowl',
    'Mer-kin gladiator mask',
    'Mer-kin headguard',
    'Mer-kin scholar mask',
    'Mer-kin sneakmask',
    'moist sailor\'s cap',
    'The Necbromancer\'s Hat',
    'no hat',
    'norwhal helmet',
    'nurse\'s hat',
    'Ol\' Scratch\'s stovepipe hat',
    'orange peel hat',
    'rusty diving helmet',
    'sea cowboy hat',
    'shapeless wide-brimmed hat',
    'slime-covered helmet',
    'sponge helmet',
    'straw hat',
    'ten-gallon hat',
    'Uncle Hobo\'s stocking cap',
    'water-polo cap',
    'wreath of laurels',
    'Zombo\'s skullcap',
    'duct tape fedora',
    'stone baseball cap',
    'bat hat',
    'catskin cap',
    'nasty rat mask',
    'nine-gallon hat',
    'plexiglass pith helmet',
    'honeycap',
    'toy space helmet',
    'wool hat',
    'beer helmet',
    'ghast iron Garibaldi',
    'lynyrdskin cap',
    'mummy mask',
    'reinforced beaded headband',
    'black cowboy hat',
    'dwarvish war helmet',
    'mesh cap',
    'snailmail coif',
    'star hat',
    'big bad voodoo mask',
    'black helmet',
    'cold water bottle',
    'eight-gallon hat',
    'guard turtle shell',
    'sealhide hood',
    'giant discarded bottlecap',
    'spaghetti cult mask',
    'antique nutcracker hat',
    'biomechanical crimborg helmet',
    'brown felt tophat',
    'clingfilm cap',
    'Dolph Bossin\'s Crimbo hat',
    'extra-large palm-frond toupee',
    'fireman\'s helmet',
    'football helmet',
    'gold crown',
    'Grimacite gasmask',
    'grungy bandana',
    'Mark I Steam-Hat',
    'Mark II Steam-Hat',
    'Mark III Steam-Hat',
    'Mark IV Steam-Hat',
    'Mark V Steam-Hat',
    'panhandle panhandling hat',
    'plain paper hat',
    'Radio Free Baseball Cap',
    'rave visor',
    'sleep mask',
    'spangly sombrero',
    'Voluminous Radio Hat',
    'warbear feathered fedora',
    'warbear lined ushanka',
    'warbear spiked helm',
    'wolf mask',
    'Mohawk wig',
    'seven-gallon hat',
    'fuzzy busby',
    'fuzzy earmuffs',
    'fuzzy montera',
    'spiky turtle helmet',
    'dilapidated wizard hat',
    'giant yellow hat',
    'Grimacite goggles',
    'muddy pirate hat',
    'worn tophat',
    'bellhop\'s hat',
    'bonedanna',
    'chrome helmet turtle',
    'fez of etymology',
    'fiberglass fedora',
    'Helm of the Scream Emperor',
    'marble mariachi hat',
    'porcelain porkpie',
    'six-gallon hat',
    'wooden salad bowl',
    'wrought-iron wig',
    'enchantlers',
    'oil cap',
    'Snow Queen Crown',
    'f3d0r4',
    'heavy crown',
    'moose antlers',
    'pointy red hat',
    'yabba dabba doo rag',
    'All-Hallow\'s Steve\'s fright wig',
    'Ancient Saucehelm',
    'Big Candy\'s tophat',
    'Boris\'s Helm',
    'Boris\'s Helm (askew)',
    'bounty-hunting helmet',
    'bowler',
    'Brogre bucket hat',
    'centurion helmet',
    'Colander of Em-er\'il',
    'Crimbo hat',
    'The Crown of Ed the Undying',
    'Crown of Thrones',
    'depleted Grimacite ninja mask',
    'Disco \'Fro Pick',
    'draggin\' ball hat',
    'El Sombrero De Lopez',
    'Elder Turtle Shell',
    'eXtreme scarf',
    'fancy tophat',
    'five-gallon hat',
    'floaty rock helmet',
    'Hairpiece On Fire',
    'high-temperature mining mask',
    'ice pick',
    'iron helmet',
    'isotophat',
    'linoleum helmet turtle',
    'makeshift turban',
    'Moonthril Circlet',
    'outrageous sombrero',
    'oxygenated eggnog helmet',
    'papier-mitre',
    'plaid cowboy hat',
    'Scalp of Gorgolok',
    'Seasonal Beret',
    'sinister demon mask',
    'space beast fur hat',
    'spelunker\'s fedora',
    'spooky hockey mask',
    'Spooky Putty mitre',
    'sugar chapeau',
    'sweatband',
    'time helmet',
    'tin tam',
    'training helmet',
    'Tropical Crimbo Hat',
    'warbear dress helmet',
    'warbear foil hat',
    'wumpus-hair wig',
    'Xiblaxian stealth cowl',
    'yak toupee',
    'Cerebral Cloche',
    'fancy ball mask',
    'lihc face',
    'pig-iron helm',
    'safarrri hat',
    'stainless steel skullcap',
    'yellow plastic hard hat',
    'cornuthaum',
    'hot daub bun',
    'asbestos helmet turtle',
    'clockwork hat',
    'cold ninja mask',
    'four-gallon hat',
    'grass hat',
    'miner\'s helmet',
    'sequined fez',
    'turtlemail coif',
    'Baron von Ratsworth\'s tophat',
    'pickelhaube',
    'willowy bonnet',
    'bubblewrap bottlecap turtleban',
    'Crown of the Goblin King',
    'demon-horned hat',
    'double-ice cap',
    'goofily-plumed helmet',
    'meaty helmet turtle',
    'powdered wig',
    'neoprene skullcap',
    'blue traffic cone',
    'filthy knitted dread sack',
    'goat beard',
    'green traffic cone',
    'helm of the white knight',
    'Knob Goblin elite helm',
    'leather mask',
    'orange traffic cone',
    'Orcish baseball cap',
    'red traffic cone',
    'suspicious-looking fedora',
    'tattered paper crown',
    'three-gallon hat',
    'yellow traffic cone',
    'barskin hat',
    'meatloaf helmet',
    'pimpin\' meat hat',
    '4-dimensional fez',
    'aerogel akubra',
    'astral chapeau',
    'balaclava',
    'balloon helmet',
    'barrelhead',
    'chalk chapeau',
    'clown wig',
    'FantasyRealm Mage\'s Hat',
    'FantasyRealm Rogue\'s Mask',
    'FantasyRealm Warrior\'s Helm',
    'gabardine garibaldi',
    'gasmask',
    'green cloth cap',
    'Knob Goblin visor',
    'leather aviator\'s cap',
    'lemon party hat',
    'paperclip turban',
    'paraffin pith helmet',
    'pixel hat',
    'PirateRealm party hat',
    'polyester panama hat',
    'radiation-resistant helmet',
    'raspberry beret',
    'real cowboy hat',
    'smooth velvet hat',
    'snow hat',
    'Sombrero De Vida',
    'sucker kabuto',
    'topeé',
    'toy Crimbot mega face',
    'warbear plain fedora',
    'warbear plain helm',
    'warbear plain ushanka',
    'wax hat',
    'basic meat fez',
    'furry green turtle',
    'irate sombrero',
    'bark beret',
    'basic meat helmet',
    'foolscap fool\'s cap',
    'ironic knit cap',
    'meat cowboy hat',
    'mullet wig',
    'pentacorn hat',
    'pottery hat',
    'turtle wax helmet',
    'two-gallon hat',
    'ancient turtle shell helmet',
    'Dolphin King\'s crown',
    'enchanted eyepatch',
    'maiden wig',
    'asshat',
    'BRICKO hat',
    'bugbear beanie',
    'chef\'s hat',
    'Cloaca-Cola helmet',
    'coconut shell',
    'Dyspepsi-Cola helmet',
    'festive holiday hat',
    'insane tophat',
    'Jarlsberg\'s hat',
    'metallic foil cat ears',
    'pail',
    'parasitic headgnawer',
    'party hat',
    'propeller beanie',
    'skeletortoise',
    'Van der Graaf helmet',
    'Ze&trade; goggles',
    'eyepatch',
    'samurai turtle helmet',
    'brown paper bag mask',
    'bum cheek',
    'crêepy mask',
    'Kentucky-style derby',
    'knobby helmet turtle',
    'one-gallon hat',
    'oversized skullcap',
    'viking helmet',
    'oriole-feather headdress',
    'silent beret',
    'anniversary concrete fedora',
    'beholed bedsheet',
    'brainwave-controlled unicorn horn',
    'dice-print do-rag',
    'Dinsey mascot mask',
    'disco mask',
    'The Emperor\'s new hat',
    'fire',
    'funny paper hat',
    'Hat O\' Nine Tails',
    'helmet turtle',
    'Hollandaise helmet',
    'indie comic hipster glasses',
    'insulting hat',
    'invisible bag',
    'jewel-eyed wizard hat',
    'Knob Goblin harem veil',
    'KoL Con 3-D Glasses',
    'makeshift yakuza mask',
    'mariachi hat',
    'mummy costume',
    'opera mask',
    'passable elf mask',
    'pumpkinhead mask',
    'ravioli hat',
    'seal-skull helmet',
    'snorkel',
    'space trooper helmet',
    'superhero mask',
    'webbed comic mask',
    'witch hat',
    'wolfman mask',
    'The Clown Crown',
    'mining helmet',
    'spelunking fedora',
    'X-ray goggles'];

const WEAP_1H = ['Blood knife',
    'Granny Hackleton\'s Gatling gun',
    'Great Wolf\'s right paw',
    'zombie accordion',
    'frying brainpan',
    'groping claw',
    'hothammer',
    'old dry bone',
    'remorseless knife',
    '7-inch discus',
    'antique spear',
    'brand new key',
    'Brimstone Bludgeon',
    'Byte',
    'cursed cutlass',
    'deep six-shooter',
    'diabolical crossbow',
    'Dinsey\'s pizza cutter',
    'dreadful glove',
    'duct tape sword',
    'fish scimitar',
    'Flail of the Seven Aspects',
    'Frosty\'s arm',
    'Frosty\'s snowball sack',
    'garbage sticker',
    'Hodgman\'s whackin\' stick',
    'The Jokester\'s gun',
    'lawn dart',
    'Mer-kin finpaddle',
    'Mer-kin hookspear',
    'Mjolnir Jr.',
    'octopus\'s spade',
    'pernicious cudgel',
    'Pigsticker of Violence',
    'rusty piece of rebar',
    'rusty speargun',
    'skate blade',
    'Sledgehammer of the Vælkyr',
    'slime-covered club',
    'slime-covered speargun',
    'soap knife',
    'Stick-Knife of Loathing',
    'super-sweet boom box',
    'teflon spatula',
    'Truthsayer',
    'Uncle Hobo\'s highest bough',
    'velcro broadsword',
    'velcro paddle ball',
    'White Dragon Fang',
    'Windsor Pan of the Source',
    'wolf whistle',
    'Wrath of the Capsaician Pastalords',
    'beer bong',
    'ghast iron cleaver',
    'goatskin umbrella',
    'honey dipper',
    'oversized pipe',
    'toy ray gun',
    'unsanitized scalpel',
    'war tongs',
    'ancient ice cream scoop',
    'combat fan',
    'dwarvish war mattock',
    'giant foam finger',
    'happiness',
    'Maxwell\'s Silver Hammer',
    'pygmy spear',
    'red-hot poker',
    'Saturday Night Special',
    'short-handled mop',
    'antique machete',
    'black blade',
    'black sword',
    'breadchucks',
    'fleetwood chain',
    'giant cactus quill',
    'giant safety pin',
    'half-size scalpel',
    'The Nuge\'s favorite crossbow',
    'pointed stick',
    'trout fang',
    'X-37 gun',
    'yohohoyo',
    'batblade',
    'C.H.U.M. knife',
    'candy knife',
    'club of the five seasons',
    'flaming sword',
    'giant artisanal rice peeler',
    'grassy cutlass',
    'grease cannon',
    'Grimacite gat',
    'heavy leather-bound tome',
    'heteroerotic frat-paddle',
    'immense cyborg hand',
    'keel-haulin\' knife',
    'love',
    'obsidian nutcracker',
    'Othello\'s dagger',
    'Pener\'s drumstick',
    'pipe wrench',
    'pygmy concertinette',
    'rainbow crossbow',
    'spectral axe',
    'star spatula',
    'vibrating cyborg knife',
    'witty rapier',
    'world\'s smallest violin',
    'broken sword',
    'crowbar',
    'frozen seal spine',
    'gatorskin umbrella',
    'rave whistle',
    'silver cheese-slicer',
    'silver paté knife',
    'star boomerang',
    'star stiletto',
    'bastard baster',
    'battery-powered drill',
    'beaver spear',
    'crazy bastard sword',
    'curmudgel',
    'eldritch hammer',
    'hand-carved bokken',
    'huge mosquito proboscis',
    'leechknife',
    'oil pan',
    'titanium assault umbrella',
    'VYKEA hex key',
    'bone crusher',
    'carrot-on-a-stick',
    'elevenderizing hammer',
    'fiberglass foil',
    'gummi sword',
    'half-melted spoon',
    'Jacob\'s rung',
    'lupine sword',
    'old school Mafia knicke½æ',
    'porcelain police baton',
    'potato pistol',
    'Ruby Rod',
    'serpentine sword',
    'silver shrimp fork',
    'Sword of Dark Omens',
    'wrought-iron whisk',
    'ghostly dagger',
    'haunted paddle-ball',
    'hawk',
    'iron pasta spoon',
    'machetito',
    'mannequin leg',
    'wicker sticker',
    'bamboo bokuto',
    'barrel gun',
    'Bonestabber',
    'bottle-rocket crossbow',
    'can of fake snow',
    'candlestick',
    'chocolate cow bone',
    'duck-on-a-string',
    'elf ploughshare',
    'elven tambourine',
    'elven whittling knife',
    'exclusive club',
    'flaming juggler\'s balls',
    'Frankly Mr. Shank',
    'haiku katana',
    'Hand that Rocks the Ladle',
    'ice nine',
    'ice sickle',
    'iFlail',
    'infernal toilet brush',
    'kiwi beak',
    'knife',
    'lead pipe',
    'lightning rod',
    'Loathing Legion double prism',
    'Loathing Legion hammer',
    'macroplane grater',
    'madius',
    'Mafia violin case',
    'Meat Tenderizer is Murder',
    'origami riding crop',
    'oversized pizza cutter',
    'papier-mâchéte',
    'papier-mâchine gun',
    'Periodical Paintbrush',
    'prehistoric spear',
    'Rain-Doh yellow laser gun',
    'reindeer hammer',
    'reindeer sickle',
    'revolver',
    'right bear arm',
    'roboduck-on-a-string',
    'rusted-out shootin\' iron',
    'Saucepanic',
    'scratch \'n\' sniff crossbow',
    'scratch \'n\' sniff sword',
    'sewage-clogged pistol',
    'Shakespeare\'s Sister\'s Accordion',
    'sharpened spoon',
    'Sheila Take a Crossbow',
    'shooting morning star',
    'silent pea shooter',
    'Sneaky Pete\'s basket',
    'soul knife',
    'space heater',
    'space needle',
    'Space Tourist Phaser',
    'spant spear',
    'spiked femur',
    'Spooky Putty ball',
    'Staff of Ed (Actually Ed the Undying)',
    'steel sword',
    'stinky cheese sword',
    'sugar shank',
    'sugar shotgun',
    'Super Magic Power Sword X',
    'Thor\'s Pliers',
    'time sword',
    'tin foil',
    'Tropical Crimbo Sword',
    'vampire duck-on-a-string',
    'Work is a Four Letter Sword',
    'wrench',
    '17-alarm Saucepan',
    'ancient stone fist',
    'anger blaster',
    'Cerebral Crossbow',
    'Chelonian Morningstar',
    'contract enforcement stick',
    'debonair deboner',
    'depleted Grimacite kneecapping stick',
    'doubt cannon',
    'elegant nightstick',
    'fear condenser',
    'grass whistle',
    'Greek Pasta Spoon of Peril',
    'Hammer of Smiting',
    'huge spoon',
    'kneecapping stick',
    'magic whistle',
    'plasma rifle',
    'regret hose',
    'stainless steel shillelagh',
    'vorpal blade',
    'broken beer bottle',
    'candy stick',
    'chopsticks',
    'clockwork crossbow',
    'corrupt club of corrupt corruption',
    'crystalline reamer',
    'grass blade',
    'Knob Goblin melon baller',
    'lead yo-yo',
    'logging hatchet',
    'Meteoid ice beam',
    'pitchfork',
    'pixel morning star',
    'quantum disintegrator pistol',
    'savory sword',
    'severed flipper',
    'spooky bicycle chain',
    'sword of static',
    'swordzall',
    'ultimate ultimate frisbee',
    'accord ion',
    'double-barreled sling',
    'finger cymbals',
    'flaming cardboard sword',
    'Frost&trade; brand sword',
    'gnawed-up dog bone',
    'grease gun',
    'hippy bongo',
    'Orcish frat-paddle',
    'slide rule',
    'boxing glove on a spring',
    'bubblewrap sword',
    'cardboard sword',
    'diamond-studded cane',
    'filthy pestle',
    'flaming crutch',
    'knob bugle',
    'muculent machete',
    'ratarang',
    'sabre teeth',
    'shotgun',
    'styrofoam sword',
    '5-Alarm Saucepan',
    'aerogel accordion',
    'astral mace',
    'astral pistol',
    'balloon sword',
    'basic meat spork',
    'Bjorn\'s Hammer',
    'blammer',
    'blunt icepick',
    'boot knife',
    'butterfly knife',
    'can of maces',
    'cheap plastic kazoo',
    'clock-cleaning hammer',
    'curdflinger',
    'deadfall branch',
    'dripping meat sword',
    'fluorescent lightbulb',
    'glow-in-the-dark dart gun',
    'Hammerus',
    'iron dagger',
    'Knob Goblin deluxe scimitar',
    'law-abiding citizen cane',
    'Mace of the Tortoise',
    'mercenary pistol',
    'Pasta Spoon of Peril',
    'pestoblade',
    'pixel boomerang',
    'pixel chain whip',
    'pixel sword',
    'poison pen',
    'polyester peeler',
    'pottery club',
    'pottery yo-yo',
    'sucker tachi',
    'tambourine',
    'toy Crimbot power glove',
    'Unionize The Elves sign',
    'warbear oil pan',
    'wooden spoon',
    'corrupt club of corruption',
    'Dr. Hobo\'s scalpel',
    'dreadlock whip',
    'Gnollish flyswatter',
    'Gnollish plunger',
    'ironic battle spoon',
    'jack flapper',
    'plastic replica blaster pistol',
    'sealhide whip',
    'starchy crossbow',
    'starchy sword',
    'suede shortsword',
    'western-style skinning knife',
    'white sword',
    'Bananubis\'s Staff',
    'bat whip',
    'boomerang',
    'bone rattle',
    'breadwand',
    'cardboard katana',
    'cardboard wakizashi',
    'cheap plastic blowgun',
    'cheap plastic bottle opener',
    'Cloaca-Cola-issue combat knife',
    'eggbeater',
    'electric crutch',
    'evil paper umbrella',
    'Gnollish slotted spoon',
    'halfberd',
    'huge mirror shard',
    'Knob Goblin spatula',
    'little paper umbrella',
    'obsidian dagger',
    'palm-frond whip',
    'parasitic claw',
    'portable corkscrew',
    'rattail whip',
    'rubber band gun',
    'rubber spatula',
    'sewer snake',
    'shiny butcherknife',
    'skeleton bone',
    'spork',
    'sturdy machete',
    'tail o\' nine cats',
    'throwing wrench',
    'trusty torch',
    'trusty whip',
    'Wand of Nagamar',
    'asparagus knife',
    'bonerang',
    'boning knife',
    'club of corruption',
    'corn holder',
    'cap gun',
    'dented harmonica',
    'dishrag',
    'fouet de tortue-dressage',
    'gnauga hide whip',
    'Gnollish pie server',
    'hippo whip',
    'Knob Goblin scimitar',
    'Knob Goblin tongs',
    'penguin whip',
    'remaindered axe',
    'scorpion whip',
    'space beast fur whip',
    'sweet ninja sword',
    'tiny ninja sword',
    'wumpus-hair whip',
    'yak whip',
    'airblaster gun',
    'bar whip',
    'bucket of anniversary lard',
    'candy knuckles',
    'can-you-dig-it?',
    'chisel',
    'clown hammer',
    'clown whip',
    'cool whip',
    'costume sword',
    'demon whip',
    'disco ball',
    'hilarious comedy prop',
    'lavalarva',
    'licorice whip',
    'live wire',
    'Mayor Ghost\'s gavel',
    'Murderbot whip',
    'The Necbromancer\'s Wizard Staff',
    'pasta spoon',
    'pixel whip',
    'rope',
    'saucepan',
    'seal-clubbing club',
    'Spelunker\'s whip',
    'Spooky Putty snake',
    'Staff of Blood and Pudding',
    'Staff of Fruit Salad',
    'Staff of Holiday Sensations',
    'Staff of Queso Escusado',
    'Staff of Simmering Hatred',
    'Staff of the All-Steak',
    'Staff of the Black Kettle',
    'Staff of the Cozy Fish',
    'Staff of the Cream of the Cream',
    'Staff of the Deepest Freeze',
    'Staff of the Electric Range',
    'Staff of the Grand Flambé',
    'Staff of the Grease Trap',
    'Staff of the Greasefire',
    'Staff of the Headmaster\'s Victuals',
    'Staff of the Healthy Breakfast',
    'Staff of the Hearty Dinner',
    'Staff of the Kitchen Floor',
    'Staff of the Light Lunch',
    'Staff of the Lunch Lady',
    'Staff of the Midnight Snack',
    'Staff of the November Jack-O-Lantern',
    'Staff of the Roaring Hearth',
    'Staff of the Scummy Sink',
    'Staff of the Short Order Cook',
    'Staff of the Soupbone',
    'Staff of the Staff of Life',
    'Staff of the Standalone Cheese',
    'Staff of the Teapot Tempest',
    'Staff of the Walk-In Freezer',
    'Staff of the Well-Tempered Cauldron',
    'Staff of the Woodfire',
    'sticky hand whip',
    'stuffed club',
    'stuffed crazy bastard sword',
    'tiny plastic sword',
    'toy taijijian',
    'turtle totem',
    'twisted-up wet towel',
    'white whip',
    'KoL Con 12-gauge',
    'turtleslinger'];

const WEAP_2H = ['Great Wolf\'s rocket launcher',
    'Unkillable Skeleton\'s restless leg',
    'Unkillable Skeleton\'s sawsword',
    'bag of unfinished business',
    'Bigger Bugfinder Blade',
    'bindlestocking',
    'Bloodbath',
    'Chester\'s bag of candy',
    'Coily&trade;',
    'cozy bazooka',
    'cozy scimitar',
    'decaying wooden oar',
    'El Vibrato energy spear',
    'FDKOL fire hose',
    'fetus-smashing club',
    'fire axe',
    'fish bazooka',
    'fish stick',
    'flamin\' bindle',
    'freezin\' bindle',
    'Frosty\'s nailbat',
    'giant fishhook',
    'giant shrimp fork',
    'giant turkey leg',
    'Ginsu&trade;',
    'halibut',
    'Meatcleaver',
    'Mer-kin digpick',
    'Mer-kin dodgeball',
    'Mer-kin dragnet',
    'Mer-kin switchblade',
    'miniature deck cannon',
    'non-stick pugil stick',
    'Ol\' Scratch\'s infernal pitchfork',
    'PVC staff',
    'rusty staff',
    'Seeger\'s Unstoppable Banjo',
    'skate board',
    'sleazy bindle',
    'slime-covered shovel',
    'slime-covered staff',
    'spooky bindle',
    'stinkin\' bindle',
    'Sword of Procedural Generation',
    'The Trickster\'s Trikitixa',
    'triple barreled barrel gun',
    'Underworld flail',
    'Underworld truncheon',
    'villainous scythe',
    'Zim Merman\'s guitar',
    'Zombo\'s shoulder blade',
    'beer-a-pult',
    'cast-iron legacy paddle',
    'fire poi',
    'giant driftwood sculpture',
    'massive sitar',
    'alarm accordion',
    'Bugfinder Blade',
    'didgeridooka',
    'perforated battle paddle',
    'plexiglass pikestaff',
    'charming flute',
    'denim axe',
    'Drowsy Sword',
    'peace accordion',
    'star crossbow',
    'star staff',
    'star sword',
    'accordionoid rocca',
    'arse-shooting crossbow',
    'coal shovel',
    'creepy-ass club',
    'cyber-mattock',
    'evil-ass club',
    'frigid-ass club',
    'giant discarded plastic fork',
    'heavy metal thunderrr guitarrr',
    'hot-ass club',
    'jungle drum',
    'magilaser blastercannon',
    'nasty-ass club',
    'pewter claymore',
    'tommy gun',
    'a butt tuba',
    'automatic catapult',
    'backwoods banjo',
    'bill bec-de-bardiche glaive-guisarme',
    'bugbear-smiting sword',
    'C.B.F.G.',
    'double barreled barrel gun',
    'drywall axe',
    'giant needle',
    'mercenary rifle',
    'Radio Free Foil',
    'toxic mop',
    'acoustic guitarrr',
    'armgun',
    'black kettle drum',
    'carob cannon',
    'ghost accordion',
    'hairy staff',
    'ram-battering staff',
    'ridiculously huge sword',
    'Spirit Precipice',
    'autocalliope',
    'bad-ass club',
    'ga-ga radio',
    'Grimacite glaive',
    'hand-carved bow',
    'hand-carved staff',
    'hot cross bow',
    'lucky ball-and-chain',
    'meatspout staff',
    'projectile icemaker',
    'shuddersword',
    'smoldering staff',
    'staph of homophones',
    'sword behind inappropriate prepositions',
    'asbestos sword',
    'bone and arrows',
    'buffalo blade',
    'chrome crossbow',
    'giant cheesestick',
    'lawnmower blade',
    'linoleum staff',
    'non-Euclidean non-accordion',
    'ocarina of space',
    'ram stick',
    'two-handed depthsword',
    'Accordion of Jordion',
    'asbestos crossbow',
    'bone flute',
    'chrome staff',
    'linoleum sword',
    'sack of doorknobs',
    'asbestos staff',
    'big stirring stick',
    'bounty-hunting rifle',
    'bow staff',
    'chrome sword',
    'Crimbo sword',
    'Crimbomination Contraption',
    'depleted Grimacite hammer',
    'giant candy cane',
    'goulauncher',
    'The Landscaper\'s leafblower',
    'linoleum crossbow',
    'Loathing Legion chainsaw',
    'Loathing Legion flamethrower',
    'Moonthril Flamberge',
    'Moonthril Longbow',
    'plastic nunchaku',
    'Rain-Doh violet bo',
    'plastic guitar',
    'ridiculously overelaborate ninja weapon',
    'Shakespeare\'s Sister\'s Accordion',
    'snow shovel',
    'soylent staff',
    'Staff of Fats',
    'Staff of Fats (Actually Ed the Undying)',
    'sugar shillelagh',
    'Super Crimboman Ultra Mega Hypersword',
    'tin drum',
    'Trusty',
    'foot-long hot daub',
    'icy-hot katana',
    'ninja mop',
    'pentatonic accordion',
    'Shagadelic Disco Banjo',
    'Squeezebox of the Ages',
    '4-dimensional guitar',
    '7-Foot Dwarven mattock',
    'boilgun',
    'bone bandoneon',
    'bubble bauble bow',
    'can cannon',
    'clockwork staff',
    'clockwork sword',
    'Crimbo ukulele',
    'crowbarrr',
    'elephant stinger',
    'flypaper staff',
    'frigid hankyū',
    'frozen nunchaku',
    'giant spider leg',
    'goblin autoblowgun',
    'goblin hunting spear',
    'rib of the Bonerdagon',
    'rusty grave robbing shovel',
    'savory crossbow',
    'savory staff',
    'squeaky staff',
    'wholeberd',
    'wiffle-flail',
    '25-meat staff',
    'flamingo mallet',
    'Kentucky-fried meat crossbow',
    'Kentucky-fried meat staff',
    'Kentucky-fried meat sword',
    'repeating crossbow',
    'Totally Gay Claymore',
    'accordion file',
    'BRICKO sword',
    'bubblewrap crossbow',
    'bubblewrap staff',
    'cardboard crossbow',
    'cardboard staff',
    'dense meat crossbow',
    'dense meat staff',
    'dense meat sword',
    'eXtreme meat crossbow',
    'eXtreme meat staff',
    'eXtreme meat sword',
    'glistening staff',
    'Gnollish autoplunger',
    'infernal fife',
    'Knob Goblin elite polearm',
    'pair of bolt cutters',
    'poutine pole',
    'slightly peevedbow',
    'styrofoam crossbow',
    'styrofoam staff',
    'wooden axe',
    'astral bludgeon',
    'astral longbow',
    'Ax of L\'rose',
    'bal-musette accordion',
    'Cajun accordion',
    'deathchucks',
    'Disco Banjo',
    'dripping meat crossbow',
    'dripping meat staff',
    'gift-a-pult',
    'guancertina',
    'high-energy mining laser',
    'high-temperature mining drill',
    'inflatable baseball bat',
    'office-supply crossbow',
    'quirky accordion',
    'Red Rover BB gun',
    'Rock and Roll Legend',
    'Skipper\'s accordion',
    'warbear exhaust manifold',
    'worm-riding hooks',
    'big bass drum',
    'calavera concertina',
    'dueling banjo',
    'half-sized guitar',
    'mama\'s squeezebox',
    'pocket theremin',
    'pool cue',
    'rubber axe',
    'spooky staff',
    'starchy staff',
    'weighted paperclip chain',
    'amok putter',
    'baritone accordion',
    'Barney\'s rake',
    'beer-soaked mop',
    'grave robbing shovel',
    'out-of-tune biwa',
    'spooky stick',
    'stone banjo',
    'third-hand nunchaku',
    'wooden stakes',
    'basic meat crossbow',
    'basic meat staff',
    'basic meat sword',
    'beer-battered accordion',
    'slingshot',
    'soup-chucks',
    'antique accordion',
    'archaeologing shovel',
    'big stick',
    'KoL Con Cinco Piñata Bat',
    'stolen accordion',
    'toy accordion',
    'trash net',
    'Tales of the Word Realms',
    'gnollish nunchaku'];

const OFFHAND = ['Great Wolf\'s left paw',
    'antique spyglass',
    'enchanted fire extinguisher',
    'Hodgman\'s almanac',
    'Hodgman\'s cane',
    'Hodgman\'s garbage sticker',
    'Hodgman\'s harmonica',
    'Hodgman\'s imaginary hamster',
    'Hodgman\'s metal detector',
    'Hodgman\'s varcolac paw',
    'The Necbromancer\'s Stein',
    'Ol\' Scratch\'s ash can',
    'Ol\' Scratch\'s stove door',
    'old school flying disc',
    'Oscus\'s garbage can lid',
    'pixel grappling hook',
    'red wagon',
    'slime-covered compass',
    'slime-covered lantern',
    'snowstick',
    'tailbone shield',
    'trench lighter',
    'vengeful spirit',
    'Wand of Oscus',
    'Zombo\'s shield',
    'cup of infinite pencils',
    '\'WILL WORK FOR BOOZE\' sign',
    'C.H.U.M. lantern',
    'grisly shield',
    'left-handed melodica',
    'makeshift castanets',
    'marinara jug',
    'Scepter of Loathing',
    'sealskin drum',
    'spaghetti-box banjo',
    'washboard shield',
    'Brand of Violence',
    'Cold Stone of Hatred',
    'Dinsey\'s radar dish',
    'Drunkula\'s wineglass',
    'HOA regulation book',
    'Unkillable Skeleton\'s shield',
    'spongy shield',
    'antique shield',
    'beach ball marble',
    'beige clambroth marble',
    'big bumboozer marble',
    'black catseye marble',
    'brass dorsal fin',
    'brown crock marble',
    'bumblebee marble',
    'collapsible baton',
    'Dallas Dynasty Falcon Crest shield',
    'eelskin shield',
    'glowing esca',
    'green peawee marble',
    'jet bennie marble',
    'lemonade marble',
    'Mer-kin begsign',
    'Mer-kin roundshield',
    'Mer-kin stopwatch',
    'Mer-kin takebag',
    'red China marble',
    'rusty old lantern',
    'silver cow creamer',
    'steely marble',
    'teflon shield',
    'velcro shield',
    'vinyl shield',
    'duct tape buckler',
    'catskin buckler',
    'ghast iron heater shield',
    'sawblade shield',
    'steaming evil',
    'keg shield',
    'red X Shield',
    'six-rainbow shield',
    'smirking shrunken head',
    'wicker shield',
    'wonderwall shield',
    'star buckler',
    'battered hubcap',
    'black shield',
    'little black book',
    'sealhide buckler',
    'giant penguin keychain',
    'antique Canadian lantern',
    'Glowstick on a string',
    'portable dam',
    'red book',
    'skull gearshift knob',
    'sommelier\'s towel',
    'polyalloy shield',
    'tip jar',
    'fake washboard',
    'shield of the Skeleton Lord',
    'spiky turtle shield',
    'Wal-Mart snowglobe',
    'cuddly teddy bear',
    'heavy-duty clipboard',
    'creepy voice box',
    'Elizabeth\'s Dollie',
    'oil lamp',
    'painted shield',
    'rubber ribcage',
    'Tuesday\'s ruby',
    'bowl of petunias',
    'snake shield',
    'snarling wolf shield',
    'bakelite bowl',
    'basaltamander buckler',
    'borg sock monkey',
    'cyborg doll',
    'fiberglass fetish',
    'hors d\'oeuvre tray',
    'incredibly creepy marionette',
    'killer rag doll',
    'mad scientist\'s sock monkey',
    'marble mignonette bowl',
    'marionette',
    'marionette collective',
    'nozzle of the Phoenix',
    'porcelain pepper mill',
    'rag doll',
    'sock monkey',
    'terra cotta tambourine',
    'Whatsian Ionic Pliers',
    'Abyssal ember',
    'ancient hot dog wrapper',
    'blue LavaCo Lamp&trade;',
    'Creepy doll head',
    'depleted Grimacite gravy boat',
    'detour shield',
    'Dungeon Fist gauntlet',
    'easter egg balloon',
    'Ellsbury\'s skull',
    'Engorged Sausages and You',
    'green LavaCo Lamp&trade;',
    'iShield',
    'jar of frostigkraut',
    'oyster egg balloon',
    'padded tortoise',
    'psychic\'s crystal ball',
    'radiator heater shield',
    'red LavaCo Lamp&trade;',
    'rxr shield',
    'shadowy seal eye',
    'slippery when wet shield',
    'speed limit shield',
    'stop shield',
    'stress ball',
    'tortoboggan shield',
    'vampire pellet',
    'yield shield',
    'loadstone',
    'antique nutcracker drumstick',
    'Brimstone Bunker',
    'dirty rigging rope',
    'flaming talons',
    'gnauga hide buckler',
    'hippo skin buckler',
    'penguin skin buckler',
    'yakskin buckler',
    'ancient stone head',
    'Orcish stud-finder',
    'arm buzzer',
    'clockwork detective skull',
    'creme brulee torch',
    'demon buckler',
    'LOV Elephant',
    'white satin shield',
    'Yorick',
    'bottle of Goldschnöckered',
    'deck of lewd playing cards',
    'Ancient calendar',
    'cardboard box turtle',
    'double-ice box',
    'eye of the Tiger-lily',
    'Glass Balls of the Goblin King',
    'paint palette',
    'snapdragon pistil',
    'party crasher',
    'pumpkin spice candle',
    'spant shield',
    'sprinkle-begging cup',
    'clownskin buckler',
    'disturbing fanfic',
    'Grey Guanon',
    'hot plate',
    'meat shield',
    'portable Othello set',
    'rusty compass',
    'novelty monorail ticket',
    'Science Notebook',
    'balloon shield',
    'basic meat foon',
    'box turtle',
    'coffin lid',
    'enchanted brass knuckles',
    'fancy marzipan briefcase',
    'fancy opera glasses',
    'flimsy clipboard',
    'foon of fearfulness',
    'foon of fleshiness',
    'foon of foulness',
    'foon of frigidity',
    'foon of fulmination',
    'peanut brittle shield',
    'pixel shield',
    'pocketwatch on a chain',
    'primitive alien totem',
    'Rainbow Jello Mould',
    'security flashlight',
    'standards and practices guide',
    'sturdy cane',
    'little round pebble',
    'bobble-hip hula elf doll',
    'bone abacus',
    'Heimz Fortified Kidney Beans',
    'kickback cookbook',
    'Mixed Garbanzos and Chickpeas',
    'Tesla\'s Electroplated Beans',
    'turtle wax shield',
    'glass gnoll eye',
    'lucky lighter',
    'sebaceous shield',
    '17-ball',
    '1-ball',
    '2-ball',
    '3-ball',
    '4-ball',
    '5-ball',
    '6-ball',
    '7-ball',
    '9-ball',
    'A Light that Never Goes Out',
    'adhesive tape dolly',
    'Adventurer bobblehead',
    'aerogel attache case',
    'anniversary balloon',
    'anniversary chutney sculpture',
    'arrow\'d heart balloon',
    'astral shield',
    'astral statuette',
    'Bag o\' Tricks',
    'bag of Crotchety Pine saplings',
    'bag of Laughing Willow saplings',
    'bag of Saccharine Maple saplings',
    'ball-in-a-cup',
    'barrel lid',
    'barskin buckler',
    'botanical sample kit',
    'bouquet of all-natural free-range flowers',
    'box',
    'box-in-the-box',
    'box-in-the-box-in-the-box',
    'bread basket',
    'BRICKO bulwark',
    'card sleeve',
    'Chalice of the Malkovich Prince',
    'chalk chalice',
    'charged magnet',
    'charged druidic orb',
    'Cloaca-Cola shield',
    'cobbled-together Meat detector',
    'Codex of Capsaicin Conjuration',
    'Cookbook of the Damned',
    'cosmetic football',
    'Crimbo bottomless hot cocoa mug',
    'Crimbo Elf creepy bobble-head',
    'Crimbo light-up Rudolph doll',
    'Crimbo stogie-scented room odorizer',
    'Crimbo tree flocker',
    'crumbling skull',
    'cursed coffee cup',
    'deceased crimbo tree',
    'deck of tropical cards',
    'defective skull',
    'detective skull',
    'druidic orb',
    'Dyspepsi-Cola shield',
    'encrypted micro-cassette recorder',
    'faded green protest sign',
    'faded red protest sign',
    'fake hand',
    'fireproof megaphone',
    'fishbone catcher\'s mitt',
    'fleshy lump',
    'foon',
    'Frigid Northern Beans',
    'Gazpacho\'s Glacial Grimoire',
    'geological sample kit',
    'ghostly reins',
    'giant clay ashtray',
    'giant stuffed bugbear',
    'gingerbread moneybag',
    'glass pie plate',
    'glow-in-the-dark stuffed burrowgrub',
    'Golden HP-35 Calculator',
    'golden sausage',
    'gore bucket',
    'green balloon',
    'Half a Purse',
    'hand of Mr. Cards',
    'handmade hobby horse',
    'heart-shaped balloon',
    'heavy duty umbrella',
    'heavy pickaxe',
    'Hellfire Spicy Beans',
    'hobo code binder',
    'HP-35 Calculator',
    'hypnodisk',
    'ice baby',
    'ice bucket',
    'Idol of Ak\'gyxoth',
    'ivory cue ball',
    'Jarlsberg\'s pan',
    'Jarlsberg\'s pan (Cosmic portal mode)',
    'The Joke Book of the Dead',
    'joybuzzer',
    'Kevlar balloon',
    'KoL Con 13 snowglobe',
    'KoL Con IV Pole',
    'KoL Con Six Pack',
    'KoL Con X Treasure Map',
    'Kramco Sausage-o-Matic&trade;',
    'LARP carp',
    'latte lovers member\'s mug',
    'lead umbrella',
    'left bear arm',
    'Loathing Legion abacus',
    'Loathing Legion can opener',
    'Loathing Legion corkscrew',
    'Loathing Legion defibrillator',
    'Loathing Legion electric knife',
    'Loathing Legion kitchen sink',
    'Loathing Legion many-purpose hook',
    'Loathing Legion moondial',
    'Loathing Legion pizza stone',
    'Loathing Legion tape measure',
    'loose purse strings',
    'The Lot\'s engagement ring',
    'low-budget shield',
    'magic lamp',
    'magical ice cubes',
    'Medallion of the Ventrilo Prince',
    'meteorb',
    'meteorite guard',
    'Microplushie: Bropane',
    'Microplushie: Dorkonide',
    'Microplushie: Ermahgerdic Acid',
    'Microplushie: Fauxnerditide',
    'Microplushie: Gothochondria',
    'Microplushie: Hippylase',
    'Microplushie: Hipsterine',
    'Microplushie: Hobomosome',
    'Microplushie: Otakulone',
    'Microplushie: Raverdrine',
    'Microplushie: Sororitrate',
    'mime pocket probe',
    'miniature stuffed Goth Giant',
    'mini-zeppelin',
    'misfit dolly',
    'misfit hobby horse',
    'misfit teddy bear',
    'mole skin notebook',
    'moxie magnet',
    'Mr. Balloon',
    'Mr. Haggis',
    'Mylar balloon',
    'naughty fortune teller',
    'Necrotelicomnicon',
    'off-hand balloon',
    'Operation Patriot Shield',
    'optimal spreadsheet',
    'ornate dowsing rod',
    'Ouija Board, Ouija Board',
    'oyster basket',
    'Paradaisical Cheeseburger recipe',
    'parasitic strangleworm',
    'penguin thesaurus',
    'pilgrim shield',
    'pirate hook',
    'Platinum HP-35 Calculator',
    'plush alielf',
    'plush alien hamsterpus',
    'plush dogcat',
    'plush ferrelf',
    'plush hamsterpus',
    'plush mutated alielephant',
    'plush mutated alielf',
    'polyester pad',
    'pool skimmer',
    'Pork \'n\' Pork \'n\' Pork \'n\' Beans',
    'pot',
    'pottery shield',
    'pretty bouquet',
    'Raggedy Hippy doll',
    'Rain-Doh green lantern',
    'red balloon',
    'Red Roger\'s red left hand',
    'reusable shopping bag',
    'rice bowl',
    'rock',
    'Royal scepter',
    'Sceptre of the Torremolinos Prince',
    'scissor duck',
    'set of jacks',
    'Seven Loco',
    'sewer turtle',
    'Shield of Icy Fate',
    'Shrub\'s Premium Baked Beans',
    'Silver HP-35 Calculator',
    'silver sausage',
    'Sinful Desires',
    'skull of the Bonerdagon',
    'snow mobile',
    'Solstice Shield',
    'sonar fishfinder',
    'Space Tourist palmdoctor',
    'Spanish fly trap',
    'The Spirit of Crimbo',
    'spooky little girl',
    'Sprinkle shaker',
    'stack of communist leaflets',
    'stapler bear',
    'stinky cheese wheel',
    'strange tiki idol',
    'studded sealhide shield',
    'stuffed astral badger',
    'stuffed baby gravy fairy',
    'stuffed bandersnatch',
    'stuffed Baron von Ratsworth',
    'stuffed can of asparagus',
    'stuffed caterpillar',
    'stuffed Cheshire bitten',
    'stuffed cocoabo',
    'stuffed dodecapede',
    'stuffed dodo',
    'stuffed flaming gravy fairy',
    'stuffed frozen gravy fairy',
    'stuffed ghuol whelp',
    'stuffed hand turkey',
    'stuffed key',
    'stuffed MagiMechTech MicroMechaMech',
    'stuffed martini',
    'stuffed Meat',
    'stuffed mind flayer',
    'stuffed Mob Penguin',
    'stuffed monocle',
    'stuffed pocketwatch',
    'stuffed porpoise',
    'stuffed sabre-toothed lime',
    'stuffed scary death orb',
    'stuffed sleazy gravy fairy',
    'stuffed snowy owl',
    'stuffed spooky gravy fairy',
    'stuffed stab bat',
    'stuffed stinky gravy fairy',
    'stuffed teddy butler',
    'stuffed tin of caviar',
    'stuffed treasure chest',
    'stuffed undead elbow macaroni',
    'stuffed yeti',
    'stuffed yo-yo',
    'stuffed zmobie',
    'Stupid University Diploma',
    'sucker bucket',
    'surprisingly capacious handbag',
    'Sword of the Brouhaha Prince',
    'Taco Dan\'s Taco Stand Cocktail Sauce Bottle',
    'Temporal Tempera Tube',
    'third-hand lantern',
    'thought balloon',
    'Time Lord Participation Mug',
    'Tiki lighter',
    'tiny black hole',
    'torch',
    'toy Crimbot super fist',
    'Trader Olaf\'s Exotic Stinkbeans',
    'tropical paperweight',
    'turtling rod',
    'unstable fulminate',
    'UV-resistant compass',
    'Victor, the Insult Comic Hellhound Puppet',
    'voodoo doll',
    'wad of Crovacite',
    'Walford\'s bucket',
    'white balloon',
    'wicker clicker',
    'World\'s Blackest-Eyed Peas',
    'zoological sample kit'];

interface priceData {
    price: number,
    item: Item
}

function sortPrice(a: priceData, b: priceData) {
    return b.price - a.price;
}

function getPriceData(items: string[]) {
    let slotPriceData: priceData[] = [];

    items.forEach((itemString) => {
        let item = toItem(itemString);
        if ( /*canEquip(item) && */item.tradeable && item.discardable && !item.quest && !item.gift && autosellPrice(item) > 0) {
            let slot = toSlot(item);
            let price = mallPrice(item);
            print(`Found an equippable ${item} for ${slot} at ${price}!`);

            if (slotPriceData.length < MAX_COUNT) {
                slotPriceData.push({
                    item: item,
                    price: price
                });
                slotPriceData.sort(sortPrice);
            }
            else if (price > slotPriceData[MAX_COUNT - 1].price) {
                slotPriceData.splice(MAX_COUNT - 1, 1, {
                    item: item,
                    price: price
                });
                slotPriceData.sort(sortPrice);
            }
        }
    });

    return slotPriceData;
}

export function main() {
    let priceData = new Map<string, priceData[]>();

    priceData.set('pants', getPriceData(PANTS));
    priceData.set('back', getPriceData(BACK_ITEMS));
    priceData.set('shirt', getPriceData(SHIRTS));
    priceData.set('accessory', getPriceData(ACCESSORY));
    priceData.set('hat', getPriceData(HAT));
    priceData.set('1-handed weapons', getPriceData(WEAP_1H));
    priceData.set('2-handed weapons', getPriceData(WEAP_2H));
    priceData.set('offHand', getPriceData(OFFHAND));

    priceData.forEach((slotPriceData, slot) => {
        if (slotPriceData) {
            print(`${slot}:`);
            slotPriceData.forEach((priceData) => {
                print(`${priceData.item.name} ${priceData.price}`);
            })
            print();
        }
    });
}
